export const SATELLITE_LABEL_EARTH = 'EARTH';
export const SATELLITE_LABEL_APOGEE = 'APOGEE_2000';
export const SATELLITE_LABEL_STARLINK = 'STARLINK';
export const SATELLITE_LABEL_ONEWEB = 'ONEWEB';
export const SATELLITE_LABEL_KUIPER = 'KUIPER';
export const SATELLITE_LABEL_ONEWEB_KUIPER = 'ONEWEB_KUIPER';
export const SATELLITE_LABEL_ALL = 'ALL';

export const PC_BREAKPOINTS = 1280;
export const TABLET_BREAKPOINTS = 768;
export const MOBILE_BREAKPOINTS = 414;
